name: CI and create feature tags

on:
  push:
    branches-ignore:
      - main

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  create-branch-tag:
    runs-on: ubuntu-24.04
    needs: ci
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Extract base version
        id: version
        run: |
          BASE_VERSION=$(node -p "require('./package.json').version")
          echo "base=${BASE_VERSION%%-*}" >> $GITHUB_OUTPUT

      - name: Extract branch name
        id: branch
        run: |
          # Extract PR source branch name and sanitize
          RAW_BRANCH="${{ github.head_ref }}"
          echo "$RAW_BRANCH"
          SANITIZED_BRANCH=$(git rev-parse --abbrev-ref HEAD | tr '/' '-')
          echo "$SANITIZED_BRANCH"
          echo "branch=$SANITIZED_BRANCH" >> $GITHUB_OUTPUT

      - name: Count previous branch tags
        id: counter
        run: |
          COUNT=$(git tag --list "v${{ steps.version.outputs.base }}-${{ steps.branch.outputs.branch }}.*" | wc -l)
          NEXT=$((COUNT))
          echo "next=$NEXT" >> $GITHUB_OUTPUT

      - name: Create new tag
        run: |
          git tag v${{ steps.version.outputs.base}}-${{ steps.branch.outputs.branch}}.${{ steps.counter.outputs.next }}

      - name: Push changes and tag
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          push_only_tags: true
          tags: true