name: CI and bump prerelease version on main

on:
  push:
    branches:
      - main

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  
  create-release-candidate:
    runs-on: ubuntu-24.04
    needs: ci
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Bump pre-release version
        id: bump-prerelease
        run: |
          NEW_VERSION=$(npm version prerelease --preid=rc --no-git-tag-version)
          echo "version=${NEW_VERSION}" >> $GITHUB_OUTPUT

      - name: Commit pre-release bump and also tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json
          git commit -m "ci: bump patch version to ${{ steps.bump-prerelease.outputs.version }} [skip ci]" || echo "No changes to commit"
          git tag ${{ steps.bump.outputs.version }}

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
