name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Which type of release?'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  create-release:
    runs-on: ubuntu-24.04
    if: github.ref == 'refs/heads/main'
    needs: ci
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Release version
        id: release
        run: |
          NEW_VERSION=$(npm version ${{ github.event.inputs.release_type }} --no-git-tag-version)
          echo "version=${NEW_VERSION}" >> $GITHUB_OUTPUT

      - name: Commit release bump and also tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json
          git commit -m "ci: bump ${{ github.event.inputs.release_type }} version to ${{ steps.release.outputs.version }} [skip ci]" || echo "No changes to commit"
          git tag ${{ steps.release.outputs.version }}

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true

      - name: Bump to next pre-patch version
        id: pre-patch
        run: |
          NEW_VERSION=$(npm version prepatch --preid=rc --no-git-tag-version)
          echo "version=${NEW_VERSION}" >> $GITHUB_OUTPUT

      - name: Commit pre-patch bump and also tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json
          git commit -m "ci: bump pre-patch version to ${{ steps.pre-patch.outputs.version }} [skip ci]" || echo "No changes to commit"
          git tag ${{ steps.pre-patch.outputs.version }}

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true
